QT.core_private.VERSION = 5.12.4
QT.core_private.name = QtCore
QT.core_private.module =
QT.core_private.libs = $$QT_MODULE_LIB_BASE
QT.core_private.includes = $$QT_MODULE_INCLUDE_BASE/QtCore/5.12.4 $$QT_MODULE_INCLUDE_BASE/QtCore/5.12.4/QtCore
QT.core_private.frameworks =
QT.core_private.depends = core
QT.core_private.uses =
QT.core_private.module_config = v2 internal_module
QT.core_private.enabled_features = clock-gettime datetimeparser dlopen doubleconversion futimens getauxval glib glibc posix-libiconv icu inotify linkat poll_ppoll sha3-fast
QT.core_private.disabled_features = etw futimes getentropy gnu-libiconv iconv journald lttng poll_poll poll_pollts poll_select renameat2 slog2 statx syslog system-doubleconversion system-pcre2
QMAKE_LIBS_LIBRT = 
QMAKE_LIBS_LIBDL = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/lib/libdl.so
QMAKE_LIBS_GLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libgthread-2.0.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libglib-2.0.so
QMAKE_INCDIR_GLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/glib-2.0 /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/glib-2.0/include /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_ICONV = 
QMAKE_DEPENDS_ICU_CC = LIBDL
QMAKE_DEPENDS_ICU_LD = LIBDL
QMAKE_LIBS_ICU = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/lib/libicui18n.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/lib/libicuuc.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/lib/libicudata.so
QMAKE_LIBS_LIBATOMIC = 
