QT.webenginecore_private.VERSION = 5.13.0
QT.webenginecore_private.name = QtWebEngineCore
QT.webenginecore_private.module =
QT.webenginecore_private.libs = $$QT_MODULE_LIB_BASE
QT.webenginecore_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebEngineCore/5.13.0 $$QT_MODULE_INCLUDE_BASE/QtWebEngineCore/5.13.0/QtWebEngineCore
QT.webenginecore_private.frameworks =
QT.webenginecore_private.depends = qml_private quick_private gui_private core_private webenginecore
QT.webenginecore_private.uses =
QT.webenginecore_private.module_config = v2 internal_module
QT.webenginecore_private.enabled_features = webengine-alsa webengine-embedded-build webengine-bison webengine-flex webengine-gperf webengine-host-pkg-config webengine-proprietary-codecs webengine-python2 webengine-qml webengine-system-dbus webengine-system-freetype webengine-system-glib webengine-system-glibc webengine-system-jpeg webengine-system-jsoncpp webengine-system-khr webengine-system-libdrm webengine-system-ninja webengine-system-nss webengine-system-opus webengine-system-zlib webengine-v8-snapshot webengine-v8-snapshot-support webengine-widgets
QT.webenginecore_private.disabled_features = webengine-arm-thumb webengine-printing-and-pdf webengine-kerberos webengine-pepper-plugins webengine-poppler-cpp webengine-pulseaudio webengine-sanitizer webengine-system-ffmpeg webengine-system-fontconfig webengine-system-gn webengine-system-harfbuzz webengine-system-icu webengine-system-lcms2 webengine-system-libevent webengine-system-libvpx webengine-system-libwebp webengine-system-libxml2 webengine-system-minizip webengine-system-png webengine-system-protobuf webengine-system-re2 webengine-system-snappy webengine-system-x11 webengine-system-xcomposite webengine-system-xcursor webengine-system-xi webengine-system-xtst webengine-webrtc webengine-win-compiler64 webengine-winversion
QMAKE_LIBS_WEBENGINE_DBUS = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libdbus-1.so
QMAKE_INCDIR_WEBENGINE_DBUS = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/dbus-1.0 /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/dbus-1.0/include
QMAKE_LIBS_WEBENGINE_FREETYPE = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libfreetype.so
QMAKE_INCDIR_WEBENGINE_FREETYPE = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/freetype2 /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE_GLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libglib-2.0.so
QMAKE_INCDIR_WEBENGINE_GLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/glib-2.0 /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/glib-2.0/include /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE_JPEGLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libjpeg.so
QMAKE_INCDIR_WEBENGINE_JPEGLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE_JSONCPP = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libjsoncpp.so
QMAKE_INCDIR_WEBENGINE_JSONCPP = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE_LIBDRM = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libdrm.so
QMAKE_INCDIR_WEBENGINE_LIBDRM = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/libdrm
QMAKE_LIBS_WEBENGINE_NSS = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libnss3.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libnssutil3.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libsmime3.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libssl3.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libplds4.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libplc4.so /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libnspr4.so
QMAKE_INCDIR_WEBENGINE_NSS = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/nss /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/nspr
QMAKE_LIBS_WEBENGINE_OPUS = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libopus.so
QMAKE_INCDIR_WEBENGINE_OPUS = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/opus
QMAKE_LIBS_WEBENGINE_ZLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libz.so
QMAKE_INCDIR_WEBENGINE_ZLIB = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
