QT.gui_private.VERSION = 5.12.4
QT.gui_private.name = QtGui
QT.gui_private.module =
QT.gui_private.libs = $$QT_MODULE_LIB_BASE
QT.gui_private.includes = $$QT_MODULE_INCLUDE_BASE/QtGui/5.12.4 $$QT_MODULE_INCLUDE_BASE/QtGui/5.12.4/QtGui
QT.gui_private.frameworks =
QT.gui_private.depends = core_private gui
QT.gui_private.uses =
QT.gui_private.module_config = v2 internal_module
QT.gui_private.enabled_features = drm_atomic evdev freetype system-freetype fontconfig gif harfbuzz ico jpeg kms linuxfb mtdev multiprocess png system-jpeg system-png tuiotouch vnc
QT.gui_private.disabled_features = xkbcommon xcb accessibility-atspi-bridge angle_d3d11_qdtd direct2d direct2d1_1 dxgi direct3d11 direct3d11_1 direct3d9 directfb dxgi1_2 dxguid egl egl_x11 eglfs eglfs_brcm eglfs_egldevice eglfs_gbm eglfs_mali eglfs_openwfd eglfs_rcar eglfs_viv eglfs_viv_wl eglfs_vsp2 eglfs_x11 integrityfb integrityhid libinput libinput-axis-api mirclient system-harfbuzz system-xcb tslib vsp2 xlib xcb-xlib
QMAKE_LIBS_DRM = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libdrm.so
QMAKE_INCDIR_DRM = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/libdrm
QMAKE_DEPENDS_FREETYPE_CC = ZLIB
QMAKE_DEPENDS_FREETYPE_LD = ZLIB
QMAKE_LIBS_FREETYPE = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libfreetype.so
QMAKE_INCDIR_FREETYPE = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/freetype2 /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_DEPENDS_FONTCONFIG_CC = FREETYPE
QMAKE_DEPENDS_FONTCONFIG_LD = FREETYPE
QMAKE_LIBS_FONTCONFIG = -lfontconfig
QMAKE_LIBS_GBM = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libgbm.so
QMAKE_INCDIR_GBM = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_MTDEV = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libmtdev.so
QMAKE_INCDIR_MTDEV = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_LIBJPEG = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot/usr/lib/libjpeg.so
QMAKE_DEPENDS_LIBPNG_CC = ZLIB
QMAKE_DEPENDS_LIBPNG_LD = ZLIB
QMAKE_LIBS_LIBPNG = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/libpng12.so
QMAKE_INCDIR_LIBPNG = /srv/jenkins/workspace/qt-5.12.4-builder/SDK-B288/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/libpng12
