QT.webengine_private.VERSION = 5.11.2
QT.webengine_private.name = QtWebEngine
QT.webengine_private.module =
QT.webengine_private.libs = $$QT_MODULE_LIB_BASE
QT.webengine_private.includes = $$QT_MODULE_INCLUDE_BASE/QtWebEngine/5.11.2 $$QT_MODULE_INCLUDE_BASE/QtWebEngine/5.11.2/QtWebEngine
QT.webengine_private.frameworks =
QT.webengine_private.depends = webengine
QT.webengine_private.uses =
QT.webengine_private.module_config = v2 internal_module
QT.webengine_private.enabled_features = webengine-alsa webengine-bison webengine-embedded-build webengine-flex webengine-gperf webengine-host-pkg-config webengine-proprietary-codecs webengine-python2 webengine-system-dbus webengine-system-fontconfig webengine-system-freetype webengine-system-glib webengine-system-glibc webengine-system-jpeg webengine-system-jsoncpp webengine-system-khr webengine-system-libdrm webengine-system-ninja webengine-system-nss webengine-system-opus webengine-system-zlib webengine-ui-delegates webengine-v8-snapshot webengine-v8-snapshot-support
QT.webengine_private.disabled_features = webengine-geolocation webengine-pepper-plugins webengine-printing-and-pdf webengine-pulseaudio webengine-sanitizer webengine-system-ffmpeg webengine-system-gn webengine-system-harfbuzz webengine-system-icu webengine-system-lcms2 webengine-system-libevent webengine-system-libsrtp webengine-system-libvpx webengine-system-libwebp webengine-system-libxml2 webengine-system-minizip webengine-system-png webengine-system-protobuf webengine-system-re2 webengine-system-snappy webengine-system-xcomposite webengine-system-xcursor webengine-system-xi webengine-system-xrandr webengine-system-xtst webengine-testsupport webengine-webrtc webengine-winversion
QMAKE_LIBS_WEBENGINE-DBUS = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -ldbus-1
QMAKE_INCDIR_WEBENGINE-DBUS = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/dbus-1.0 /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/dbus-1.0/include
QMAKE_LIBS_WEBENGINE-FONTCONFIG = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -lfontconfig -lfreetype
QMAKE_INCDIR_WEBENGINE-FONTCONFIG = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//srv/jenkins/workspace/SDK-GEN/output-A13/host/usr/arm-obreey-linux-gnueabi/sysroot/usr/include /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//srv/jenkins/workspace/SDK-GEN/output-A13/host/usr/arm-obreey-linux-gnueabi/sysroot/usr/include/freetype2 /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/freetype2
QMAKE_LIBS_WEBENGINE-FREETYPE = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -lfreetype
QMAKE_INCDIR_WEBENGINE-FREETYPE = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/freetype2 /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE-GLIB = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -lglib-2.0
QMAKE_INCDIR_WEBENGINE-GLIB = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/glib-2.0 /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib/glib-2.0/include /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE-JPEGLIB = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -ljpeg
QMAKE_INCDIR_WEBENGINE-JPEGLIB = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE-JSONCPP = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -ljsoncpp
QMAKE_INCDIR_WEBENGINE-JSONCPP = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
QMAKE_LIBS_WEBENGINE-LIBDRM = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -ldrm
QMAKE_INCDIR_WEBENGINE-LIBDRM = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/libdrm
QMAKE_LIBS_WEBENGINE-NSS = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -lnss3 -lnssutil3 -lsmime3 -lssl3 -lplds4 -lplc4 -lnspr4
QMAKE_INCDIR_WEBENGINE-NSS = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/nss /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/nspr
QMAKE_LIBS_WEBENGINE-OPUS = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -lopus
QMAKE_INCDIR_WEBENGINE-OPUS = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include/opus
QMAKE_LIBS_WEBENGINE-ZLIB = -L/srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/lib -lz
QMAKE_INCDIR_WEBENGINE-ZLIB = /srv/jenkins/workspace/qt-5.11.2-builder/SDK-A13/usr/arm-obreey-linux-gnueabi/sysroot//usr/include
